SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME FROM SRIS
ORDER BY STUDENT_NAME

UPDATE SRIS SET SRIS.STUDENT_NAME= SS.STUDENT_NAME FROM SRIS JOIN SRIS SS ON SRIS.STUDENT_NUMBER=SS.STUDENT_NUMBER 
WHERE SRIS.STUDENT_NUMBER = SS.STUDENT_NUMBER 

SELECT DISTINCT SRIS.STUDENT_NUMBER,SS.STUDENT_NAME FROM SRIS JOIN SRIS SS ON SRIS.STUDENT_NUMBER = SS.STUDENT_NUMBER 
WHERE SRIS.STUDENT_NUMBER LIKE SS.STUDENT_NUMBER 

UPDATE SRIS SET STUDENT_NUMBER='20'+STUDENT_NUMBER WHERE STUDENT_NUMBER LIKE '0%'

SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME FROM SRIS
WHERE STUDENT_NUMBER LIKE '20%'

SELECT