SELECT DISTINCT SRIS.SUBJECT_CODE,SRIS.SUBJECT_DESCRIPTION,SRIS.UNITS FROM SRIS 
WHERE SRIS.SUBJECT_CODE IN (
SELECT DISTINCT SRIS.SUBJECT_CODE,SRIS.SUBJECT_DESCRIPTION,SRIS.UNITS FROM SRIS

FULL OUTER JOIN TBL_SUBJECT ON SRIS.SUBJECT_CODE=TBL_SUBJECT.CODE 

WHERE SRIS.SUBJECT_CODE!=TBL_SUBJECT.code)

SELECT distinct tbl_subject.code FROM tbl_subject inner JOIN SRIS ON tbl_subject.code=SRIS.SUBJECT_CODE 
where tbl_subject.code=SRIS.SUBJECT_CODE 


UPDATE SRIS SET SUBJECT_ID=tbl_subject.ID FROM SRIS INNER JOIN tbl_subject ON SRIS.SUBJECT_CODE=TBL_SUBJECT.CODE 
where tbl_subject.code=SRIS.SUBJECT_CODE 


 

INSERT INTO TBL_SUBJECT (code,description,units,isdeleted) SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,'0' FROM SRIS WHERE SUBJECT_ID IS NULL

SELECT DISTINCT SUBJECT_ID FROM SRIS

SELECT * FROM SRIS WHERE SUBJECT_ID IS NULL


update sris set STUDENT_ID=tbl_student.id from sris inner join tbl_student
on STUDENT_NUMBER=tbl_student.number where STUDENT_NUMBER=tbl_student.number