SELECT DISTINCT SUBJECT_DESCRIPTION,SUBJECT_CODE FROM SRIS ORDER BY SUBJECT_DESCRIPTION

UPDATE SRIS SET SUBJECT_CODE='-' WHERE SUBJECT_CODE IS NULL



UPDATE SRIS SET SUBJECT_DESCRIPTION='BUHAY, GAWAIN AT MGA SINULAT NI RIZAL' 
WHERE SUBJECT_DESCRIPTION ='BUHAY, GAWAIN AT KAISIPAN NI RIZAL' OR SUBJECT_DESCRIPTION =
'BUHAY, GAWAIN AT SINULAT NI RIZAL' OR SUBJECT_DESCRIPTION =
'BUHAY AT GAWAIN NG BAYANING RIZAL'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PRINCIPLES & TECHNIQUES OF ADVERTISING' 
WHERE SUBJECT_DESCRIPTION ='PRIN. & TECH OF ADV.'

UPDATE SRIS SET SUBJECT_DESCRIPTION='INTRODUCTION TO ICT W/ WORD PROCESSING' 
WHERE SUBJECT_DESCRIPTION ='INTRODUCTION TO I.T W/ WORD PROCESSING' OR 
SUBJECT_DESCRIPTION ='INTRO TO ICT W/ WPROCESSING'

UPDATE SRIS SET SUBJECT_DESCRIPTION='SOFTWARE PACKAGES' 
WHERE SUBJECT_CODE ='CS 140'

UPDATE SRIS SET SUBJECT_DESCRIPTION='BASIC ECONOMICS W/ TAXATION & AGRARIAN REFORM' 
WHERE SUBJECT_CODE ='EC 100'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PAGBASA AT PAGSULAT SA IBAT-IBANG DISIPLINA'
WHERE SUBJECT_CODE ='FO 102'

UPDATE SRIS SET SUBJECT_DESCRIPTION='OBLIGATION & CONTRACTS'
WHERE SUBJECT_CODE ='LW 111'

UPDATE SRIS SET SUBJECT_DESCRIPTION='WORLD LITERATURE'
WHERE SUBJECT_CODE ='LT 220'

UPDATE SRIS SET SUBJECT_DESCRIPTION='INTRODUCTION TO HUMANITIES'
WHERE SUBJECT_CODE ='HU 110'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PRINCIPLES OF BUSINESS ORGANIZATION & MANAGEMENT'
WHERE SUBJECT_CODE ='MN 110'

UPDATE SRIS SET SUBJECT_DESCRIPTION='ENTREPRENEURIAL & SMALL BUSINESS MANAGEMENT'
WHERE SUBJECT_CODE ='MN 220'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PRODUCTION & OPERATIONS MANAGEMENT'
WHERE SUBJECT_CODE ='MN 313'

UPDATE SRIS SET SUBJECT_DESCRIPTION='ETHICS IN BUSINESS MANAGEMENT AND SOCIAL RESPONSIBILITY'
WHERE SUBJECT_CODE ='MN 414'

UPDATE SRIS SET SUBJECT_DESCRIPTION='BIOLOGICAL SCIENCE'
WHERE SUBJECT_CODE ='NS 210'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PRINCIPLES & TECHNIQUES OF PUBLIC RELATIONS'
WHERE SUBJECT_CODE ='PR 210'

UPDATE SRIS SET SUBJECT_DESCRIPTION='STUDY & THINKING SKILLS IN ENGLISH'
WHERE SUBJECT_CODE ='EN 110'

UPDATE SRIS SET SUBJECT_DESCRIPTION='WRITING IN THE DISCIPLINE'
WHERE SUBJECT_CODE ='EN 111'

UPDATE SRIS SET SUBJECT_DESCRIPTION='PRINCIPLES OF MONEY, CREDIT & BANKING'
WHERE SUBJECT_CODE ='FN 100'
