INSERT INTO TBL_SUBJECT SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,'0' FROM SRIS
WHERE NOT EXISTS 
(SELECT CODE,DESCRIPTION,UNITS FROM TBL_SUBJECT WHERE
SUBJECT_CODE = CODE AND SUBJECT_DESCRIPTION=DESCRIPTION AND UNITS=units)


INSERT INTO tbl_faculty
SELECT DISTINCT FACULTY_NAME,'0' FROM SRIS
WHERE NOT EXISTS 
(SELECT NAME FROM TBL_FACULTY WHERE
FACULTY_NAME = NAME) AND FACULTY_NAME IS NOT NULL ORDER BY FACULTY_NAME

UPDATE SRIS SET SUBJECT_DESCRIPTION='RELATIONS & TECHNIQUES OF PUBLIC'
WHERE SUBJECT_DESCRIPTION=' RELATIONS & TECHNIQUES OF PUBLIC'


UPDATE SRIS SET SUBJECT_ID=10959 FROM SRIS INNER JOIN tbl_subject S
ON  SUBJECT_DESCRIPTION=DESCRIPTION 
WHERE  SUBJECT_DESCRIPTION=DESCRIPTION 


UPDATE SRIS SET FACULTY_ID=ID FROM SRIS INNER JOIN tbl_faculty 
ON  FACULTY_NAME=NAME 
WHERE  FACULTY_NAME=NAME 

SELECT * FROM SRIS WHERE FACULTY_ID IS NULL OR SUBJECT_ID IS NULL OR STUDENT_ID IS NULL

UPDATE SRIS SET FACULTY_ID='55',FACULTY_NAME='-' WHERE FACULTY_ID IS NULL

SUBJECT_ID=10959 WHERE SUBJECT_ID IS NULL

SELECT * FROM tbl_faculty WHERE NAME ='-'