UPDATE SRIS SET FACULTY_NAME=REPLACE(FACULTY_NAME,'DR. ','')
WHERE FACULTY_NAME LIKE 'DR. %'
UPDATE SRIS SET FACULTY_NAME=REPLACE(FACULTY_NAME,'PROF. ','')
WHERE FACULTY_NAME LIKE 'PROF. %'
UPDATE SRIS SET FACULTY_NAME=REPLACE(FACULTY_NAME,'MS. ','')
WHERE FACULTY_NAME LIKE 'MS. %'
UPDATE SRIS SET FACULTY_NAME='-' WHERE FACULTY_NAME IS NULL


UPDATE SRIS SET STUDENT_NUMBER='19'+STUDENT_NUMBER WHERE STUDENT_NUMBER LIKE '9%'
UPDATE SRIS SET STUDENT_NUMBER='20'+STUDENT_NUMBER WHERE STUDENT_NUMBER LIKE '0%'

UPDATE SRIS SET YEAR_SECTION =  STUFF(YEAR_SECTION,
PATINDEX('%[0-9]%',YEAR_SECTION),0,' ')  WHERE YEAR_SECTION NOT LIKE '% %';

UPDATE SRIS SET SUBJECT_CODE =  STUFF(SUBJECT_CODE,
PATINDEX('%[0-9]%',SUBJECT_CODE),0,' ')  WHERE SUBJECT_CODE NOT LIKE '% %';

SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,'0' FROM SRIS
SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME,'0' FROM SRIS ORDER BY STUDENT_NAME
SELECT DISTINCT FACULTY_NAME,'0' FROM SRIS ORDER BY FACULTY_NAME

UPDATE SRIS SET SUBJECT_DESCRIPTION=
(SELECT TOP 1 SUBJECT_DESCRIPTION FROM SRIS B WHERE A.SUBJECT_CODE = B.SUBJECT_CODE 
AND SUBJECT_DESCRIPTION IS NOT NULL) FROM SRIS A
WHERE SUBJECT_CODE IS NOT NULL

UPDATE SRIS SET SUBJECT_CODE=
(SELECT TOP 1 SUBJECT_CODE FROM SRIS B WHERE A.SUBJECT_DESCRIPTION = B.SUBJECT_DESCRIPTION 
AND SUBJECT_CODE IS NOT NULL) FROM SRIS A
WHERE SUBJECT_DESCRIPTION IS NOT NULL

UPDATE SRIS SET STUDENT_NAME=
(SELECT TOP 1 STUDENT_NAME FROM SRIS B WHERE A.STUDENT_NUMBER = B.STUDENT_NUMBER 
AND STUDENT_NAME IS NOT NULL) FROM SRIS A
WHERE STUDENT_NUMBER IS NOT NULL

UPDATE SRIS SET STUDENT_NUMBER=
(SELECT TOP 1 STUDENT_NUMBER FROM SRIS B WHERE A.STUDENT_NAME = B.STUDENT_NAME 
AND STUDENT_NUMBER IS NOT NULL) FROM SRIS A
WHERE STUDENT_NAME IS NOT NULL

--DELETE SRIS AND RE-INSERT
DELETE FROM SRIS
INSERT INTO SRIS (STUDENT_NUMBER, STUDENT_NAME, FINAL_GRADE, 
REMARKS, SUBJECT_CODE, SUBJECT_DESCRIPTION, UNITS, YEAR_SECTION, SEMESTER, SY, FACULTY_NAME)
SELECT DISTINCT * FROM COMPILED

--DELETE RECORD
DELETE FROM TBL_RECORD
DELETE FROM TBL_STUDENT
DELETE FROM TBL_SUBJECT
DELETE FROM TBL_FACULTY

--INSERT INTO TBL_RECORD FROM SRIS
INSERT INTO TBL_STUDENT (NUMBER,NAME,ISDELETED)
SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME,'0' FROM SRIS ORDER BY STUDENT_NAME
INSERT INTO TBL_SUBJECT (CODE,DESCRIPTION,UNITS,ISDELETED)
SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,'0' FROM SRIS ORDER BY SUBJECT_CODE
INSERT INTO TBL_FACULTY (NAME,ISDELETED)
SELECT DISTINCT FACULTY_NAME,'0' FROM SRIS

--SELECT NULL FROM COMPILED
SELECT * FROM COMPILED WHERE [STUDENT NUMBER] IS NULL OR [STUDENT NAME] IS NULL
SELECT * FROM SRIS  WHERE [STUDENT_NUMBER] IS NULL OR [STUDENT_NAME] IS NULL

--SELECT COUNT
SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME,COUNT(REMARKS) FROM SRIS 
GROUP BY STUDENT_NUMBER,STUDENT_NAME
ORDER BY STUDENT_NAME

SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,COUNT(REMARKS) FROM SRIS 
GROUP BY SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS
ORDER BY SUBJECT_CODE


UPDATE SRIS SET STUDENT_NAME='-' WHERE STUDENT_NAME IS NULL
UPDATE SRIS SET STUDENT_NUMBER='-' WHERE STUDENT_NUMBER IS NULL
UPDATE TBL_STUDENT SET NAME='-' WHERE NAME IS NULL
UPDATE TBL_STUDENT SET NUMBER='-' WHERE NUMBER IS NULL
UPDATE SRIS SET SUBJECT_CODE='-' WHERE SUBJECT_CODE IS NULL
UPDATE SRIS SET SUBJECT_DESCRIPTION='-' WHERE SUBJECT_DESCRIPTION IS NULL
UPDATE SRIS SET UNITS='0' WHERE UNITS IS NULL
UPDATE SRIS SET FACULTY_NAME='-' WHERE FACULTY_NAME IS NULL
UPDATE TBL_SUBJECT SET CODE='-' WHERE CODE IS NULL
UPDATE TBL_SUBJECT SET DESCRIPTION='-' WHERE DESCRIPTION IS NULL
UPDATE TBL_SUBJECT SET UNITS='0' WHERE UNITS='-'
UPDATE TBL_FACULTY SET NAME='-' WHERE NAME IS NULL

UPDATE  SRIS SET SUBJECT_ID=TBL_SUBJECT.ID 
FROM SRIS INNER JOIN TBL_SUBJECT 
ON TBL_SUBJECT.DESCRIPTION=SRIS.SUBJECT_DESCRIPTION 
AND TBL_SUBJECT.CODE=SUBJECT_CODE
WHERE TBL_SUBJECT.DESCRIPTION=SRIS.SUBJECT_DESCRIPTION 
AND TBL_SUBJECT.CODE=SUBJECT_CODE

UPDATE  SRIS SET STUDENT_ID=TBL_STUDENT.ID, 
STUDENT_NUMBER=TBL_STUDENT.NUMBER
FROM SRIS INNER JOIN TBL_STUDENT 
ON TBL_STUDENT.NAME=SRIS.STUDENT_NAME AND 
TBL_STUDENT.NUMBER=SRIS.STUDENT_NUMBER
WHERE TBL_STUDENT.NAME=SRIS.STUDENT_NAME AND 
TBL_STUDENT.NUMBER=SRIS.STUDENT_NUMBER

UPDATE SRIS SET SRIS.FACULTY_ID=TBL_FACULTY.ID FROM SRIS 
INNER JOIN TBL_FACULTY
ON TBL_FACULTY.NAME=SRIS.FACULTY_NAME WHERE SRIS.FACULTY_NAME=TBL_FACULTY.NAME

SELECT * FROM TBL_RECORD WHERE STUDENT_ID IS NULL OR SUBJECT_ID IS NULL OR FACULTY_ID IS NULL

--INSERT INTO TBL_RECORD
INSERT INTO TBL_RECORD
SELECT YEAR_SECTION, FINAL_GRADE, REMARKS, SEMESTER, SY, STUDENT_ID, SUBJECT_ID,'0', FACULTY_ID
FROM   sris
