INSERT INTO tbl_course 
SELECT DISTINCT SUBSTRING(YEAR_SECTION,0,PatIndex('%[0-9]%',YEAR_SECTION)) AS YS
FROM SRIS ORDER BY YS 

INSERT INTO tbl_section

SELECT DISTINCT
SUBSTRING(YEAR_SECTION,PatIndex('%[0-9]%',YEAR_SECTION), LEN(YEAR_SECTION)) AS YS FROM SRIS 
WHERE   NOT EXISTS  (SELECT SECTION FROM TBL_SECTION) 

UPDATE SRIS SET SECTION_ID=A.ID FROM SRIS INNER JOIN TBL_SECTION A ON
SUBSTRING(YEAR_SECTION,PatIndex('%[0-9]%',YEAR_SECTION), LEN(YEAR_SECTION))=A.SECTION WHERE 
SUBSTRING(YEAR_SECTION,PatIndex('%[0-9]%',YEAR_SECTION), LEN(YEAR_SECTION))=A.SECTION
 
 SELECT * FROM SRIS WHERE sy_id IS NULL

UPDATE SRIS SET SECTION_ID='39' WHERE YEAR_SECTION='-'
UPDATE SRIS SET SEMESTER='-' WHERE SEMESTER='NO SEM'
UPDATE SRIS SET SEM_ID=A.ID FROM SRIS B INNER JOIN TBL_SEMESTER A ON
B.SEMESTER=A.semester WHERE B.SEMESTER=A.semester

UPDATE SRIS SET SY_ID=A.ID FROM SRIS b INNER JOIN TBL_SY a
ON b.sy=a.sy where b.sy=a.sy

UPDATE SRIS SET YEAR_SECTION=REPLACE(YEAR_SECTION ,'EM','BSEM') WHERE YEAR_SECTION LIKE 'EM%'
UPDATE TBL_COURSE SET COURSE='-' WHERE COURSE=''

UPDATE SRIS SET COURSE_ID=A.ID FROM SRIS INNER JOIN TBL_COURSE A
ON  SUBSTRING(YEAR_SECTION,0,PatIndex('%[0-9]%',YEAR_SECTION))=A.COURSE 
WHERE SUBSTRING(YEAR_SECTION,0,PatIndex('%[0-9]%',YEAR_SECTION))=A.COURSE

UPDATE SRIS SET COURSE_ID='1' WHERE YEAR_SECTION='-'

UPDATE SRIS SET COURSE_ID=NULL
SELECT * FROM SRIS WHERE YEAR_SECTION IS NULL


	 UPDATE SRIS SET YEAR_SECTION='-' WHERE YEAR_SECTION IS NULL OR YEAR_SECTION LIKE '%NO SECTIO%'

	  update SRIS SET YEAR_SECTION =  STUFF(YEAR_SECTION,
                 PATINDEX('%[0-9]%',YEAR_SECTION),0,' ')  WHERE YEAR_SECTION NOT LIKE '% %';

				 SELECT * FROM SRIS
				 WHERE SUBJECT_ID IS NULL
				 UPDATE SRIS SET SUBJECT_ID = '11214',FACULTY_ID='55' WHERE SUBJECT_ID IS NULL
				  AND FACULTY_ID IS NULL

				 SELECT * FROM tbl_faculty WHERE NAME='-'

				 UPDATE TBL_SUBJECT SET CODE='-', DESCRIPTION='-' WHERE ID = '11214'


SELECT * FROM SRIS WHERE STUDENT_ID IS NULL OR SUBJECT_ID IS NULL OR FACULTY_ID IS NULL


INSERT INTO TBL_STUDENT (NUMBER,NAME,ISDELETED)
SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME,'0' FROM SRIS
INSERT INTO TBL_SUBJECT (CODE,DESCRIPTION,UNITS,ISDELETED)
SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS,'0' FROM SRIS
INSERT INTO TBL_FACULTY (NAME,ISDELETED)
SELECT DISTINCT FACULTY_NAME,'0' FROM SRIS



UPDATE SRIS SET FACULTY_NAME='-' WHERE FACULTY_NAME IS NULL
UPDATE SRIS SET STUDENT_NUMBER=
(SELECT TOP 1 STUDENT_NUMBER FROM SRIS B WHERE A.STUDENT_NAME = B.STUDENT_NAME) FROM SRIS A

UPDATE SRIS SET STUDENT_NUMBER='19'+STUDENT_NUMBER WHERE STUDENT_NUMBER LIKE '9%'

SELECT STUDENT_NUMBER FROM SRIS WHERE STUDENT_NUMBER LIKE '9%'

SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,UNITS FROM SRIS

UPDATE SRIS SET SUBJECT_DESCRIPTION=
(SELECT TOP 1 SUBJECT_DESCRIPTION FROM SRIS B WHERE A.SUBJECT_CODE = B.SUBJECT_CODE ) FROM SRIS A
WHERE SUBJECT_DESCRIPTION IS NULL

INSERT INTO TBL_SUBJECT 
SELECT DISTINCT SUBJECT_CODE,SUBJECT_DESCRIPTION,'0' FROM SRIS
SELECT 

SELECT * FROM SRIS
WHERE STUDENT_NUMBER LIKE '0%'


INSERT INTO TBL_STUDENT 
SELECT DISTINCT STUDENT_NUMBER,STUDENT_NAME,'0' FROM SRIS

UPDATE SRIS SET SUBJECT_ID =
(SELECT ID,CODE FROM TBL_SUBJECT A WHERE CODE IN(
SELECT DISTINCT  SUBJECT_CODE FROM SRIS WHERE SUBJECT_ID IS NULL))

UPDATE SRIS SET SUBJECT_ID ='11425'
WHERE SUBJECT_ID IS NULL AND 'MANA 4023'=SUBJECT_CODE
UPDATE SRIS SET SUBJECT_ID ='11417'
WHERE SUBJECT_ID IS NULL AND 'LAW 2013'=SUBJECT_CODE
UPDATE SRIS SET SUBJECT_ID ='11298'
WHERE SUBJECT_ID IS NULL AND 'COSC 2033'=SUBJECT_CODE
UPDATE SRIS SET SUBJECT_ID ='11423'
WHERE SUBJECT_ID IS NULL AND 'MANA 3033'=SUBJECT_CODE
UPDATE SRIS SET SUBJECT_ID ='11281'
WHERE SUBJECT_ID IS NULL AND 'ACCO 2033'=SUBJECT_CODE


UPDATE SRIS SET SUBJECT_ID ='11356' WHERE SUBJECT_ID IS NULL AND SUBJECT_CODE = 'ENMA 3103'
UPDATE SRIS SET SUBJECT_ID ='11458'	WHERE SUBJECT_ID IS NULL AND SUBJECT_CODE = 'NASC 1083'
UPDATE SRIS SET SUBJECT_ID ='11478'	WHERE SUBJECT_ID IS NULL AND SUBJECT_CODE = 'PHED 1012'
UPDATE SRIS SET SUBJECT_ID ='11491'	WHERE SUBJECT_ID IS NULL AND SUBJECT_CODE = 'PY 100'
UPDATE SRIS SET SUBJECT_ID ='11401'	WHERE SUBJECT_ID IS NULL AND SUBJECT_CODE = 'FINA 2023'

SELECT * FROM SRIS WHERE FACULTY_ID IS NULL

SELECT DISTINCT FACULTY_NAME FROM SRIS

UPDATE SRIS SET FACULTY_NAME=REPLACE(FACULTY_NAME,'DR. ','')
WHERE FACULTY_NAME LIKE 'DR. %'


SELECT * FROM SRIS WHERE STUDENT_ID IS NULL OR SUBJECT_ID IS NULL OR FACULTY_ID IS NULL
SELECT * FROM COMPILED WHERE [STUDENT NUMBER] IS NULL OR [STUDENT NAME] IS NULL 

DELETE FROM SRIS



UPDATE SRIS SET SY='-' WHERE SY IS NULL
UPDATE SRIS SET YEAR_SECTION='-' WHERE YEAR_SECTION IS NULL