USE [ERP]
GO

/****** Object:  Table [dbo].[TBL_TRAINING_COMPETENCY]    Script Date: 4/11/2018 11:43:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_TRAINING_COMPETENCY](
	[TRAINING_COMPETENCY_ID] [int] IDENTITY(1,1) NOT NULL,
	[COURSE_ID] [numeric](18, 0) NOT NULL,
	[COMPETENCY_ID] [int] NOT NULL,
	[COMPETENCY_LEVEL] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TRAINING_COMPETENCY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TBL_TRAINING_COMPETENCY]  WITH CHECK ADD FOREIGN KEY([COMPETENCY_ID])
REFERENCES [dbo].[TBL_COMPETENCY] ([COMPETENCY_ID])
GO

ALTER TABLE [dbo].[TBL_TRAINING_COMPETENCY]  WITH CHECK ADD FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[TBL_TRAINING_COURSE] ([COURSE_ID])
GO

