USE [ERP]
GO

/****** Object:  Table [dbo].[TBL_TRAINING_DEV_EMPLOYEE]    Script Date: 4/11/2018 11:43:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_TRAINING_DEV_EMPLOYEE](
	[TRAININGDEV_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_ID] [int] NULL,
	[COURSE_ID] [numeric](18, 0) NULL,
	[TRANSACTION_DATE] [date] NOT NULL DEFAULT (getdate()),
PRIMARY KEY CLUSTERED 
(
	[TRAININGDEV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TBL_TRAINING_DEV_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMP_DEV_ID] FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[TBL_EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[TBL_TRAINING_DEV_EMPLOYEE] CHECK CONSTRAINT [FK_EMP_DEV_ID]
GO

ALTER TABLE [dbo].[TBL_TRAINING_DEV_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_TRAINING_COURSE_ID] FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[TBL_TRAINING_COURSE] ([COURSE_ID])
GO

ALTER TABLE [dbo].[TBL_TRAINING_DEV_EMPLOYEE] CHECK CONSTRAINT [FK_TRAINING_COURSE_ID]
GO

