USE [ERP]
GO

/****** Object:  Table [dbo].[TBL_TRAINING_COURSE]    Script Date: 4/11/2018 11:43:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_TRAINING_COURSE](
	[COURSE_ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COURSE_TITLE] [varchar](50) NOT NULL,
	[COURSE_DESCRIPTION] [varchar](500) NOT NULL,
	[COURSE_TYPE] [varchar](10) NOT NULL,
	[COURSE_STARTDATE] [date] NULL,
	[COURSE_ENDDATE] [date] NOT NULL,
	[COURSE_TRAINING_HOURS] [varchar](20) NOT NULL,
	[COURSE_TOPIC] [varchar](50) NOT NULL,
 CONSTRAINT [PK_COURSE] PRIMARY KEY CLUSTERED 
(
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

